### ISSUE TITLE
R Error for only grey sequences

### ISSUE THREAD

**Issue by chkirschbaum** [rki-mf1/vocal#12]
If I run test with the 2022 dataset and only get grey sequences, the report can't be generated due to the following error:

Error in `chr_as_locations()`:
  ! Can't rename columns that don't exist.
  ✖ Column `cluster_ID` doesn't exist.
  Backtrace:
       ▆
    1. ├─... %>% rename(cluster_ID_in_alert_level = cluster_ID)
    2. ├─dplyr::rename(., cluster_ID_in_alert_level = cluster_ID)
    3. └─dplyr:::rename.data.frame(., cluster_ID_in_alert_level = cluster_ID)
    4.   └─tidyselect::eval_rename(expr(c(...)), .data)
    5.     └─tidyselect:::rename_impl(...)
    6.       └─tidyselect:::eval_select_impl(...)
    7.         ├─tidyselect:::with_subscript_errors(...)
    8.         │ ├─base::tryCatch(...)
    9.         │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
   10.         │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
   11.         │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
   12.         │ └─tidyselect:::with_entraced_errors(expr)
   13.         │   └─rlang::try_fetch(...)
   14.         │     └─base::withCallingHandlers(...)
   15.         └─tidyselect:::vars_select_eval(...)
   16.           └─tidyselect:::walk_data_tree(expr, data_mask, context_mask, error_call)
   17.             └─tidyselect:::eval_c(expr, data_mask, context_mask)
   18.               └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
   19.                 └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
   20.                   └─tidyselect:::as_indices_sel_impl(...)
   21.                     └─tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
   22.                       └─tidyselect:::chr_as_locations(x, vars, call = call)
   23.                         └─vctrs::vec_as_location(x, n = length(vars), names = vars)
   24.                           └─vctrs (local) `<fn>`()
   25.                             └─vctrs:::stop_subscript_oob(...)
   26.                               └─vctrs:::stop_subscript(...)
   27.                                 └─rlang::abort(...)
  Ausführung angehalten

**Comment by chkirschbaum** [comment]
To clarify about data: This error occurs on the data from the folder test. 
If you run it with `--year 2022`, this error occurs. (all sequences are grey)
If you run it with `--year 2021`, there is no error. (1 red sequence)

**Comment by silenus092** [comment]
Thanks for the info. I will have a look

**Comment by chkirschbaum** [comment]
Works now fine for me, just merged branches! Thanks a lot
